###customer indexing
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "someone",
  "fullName": "Dracula",
  "userId": "1"
}

###customer search
GET http://localhost:3000/users?text="soph"
Content-Type: application/json

