###user indexing
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "akshita",
  "fullName": "Akshita Upadhyay",
  "userId": "1"
}

###user search
GET http://localhost:3000/users?text="ak"
Content-Type: application/json

